### ISSUE TITLE
determine initial peer connection strategy

### ISSUE THREAD

**Issue by subtly** [ethereum/devp2p#11]
With regard to TCP peer connectivity:

what occurs when a node is added or removed
what occurs when a peer disconnects
what occurs during discovery
what occurs during after temporary disconnect (disconnected < 60 seconds)
what occurs during after short disconnect (disconnected < 3600 seconds; based upon idle refresh interval)
what occurs during after long disconnect (disconnected >= 3600 seconds)

**Comment by subtly** [comment]
With regard to TCP peer connectivity:
* what occurs when a node is added or removed
* what occurs when a peer disconnects
* what occurs during discovery
* what occurs during after temporary disconnect (disconnected < 60 seconds)
* what occurs during after short disconnect (disconnected < 3600 seconds; based upon idle refresh interval)
* what occurs during after long disconnect (disconnected >= 3600 seconds)

**Comment by heikoheiko** [comment]
###  Well-formedness
We benefit from well-formedness in the eth protocol as
- it guarantees that messages (blocks, txs) sent by nodes are propagated within log(n) hops
- it guarantees, that the network graphs connectedness does not by accident depend on a few nodes

### Indicators

- `closeness centrality` at a node is 1/average distance to all other nodes  (higher is better).
- `load centrality` of a node is the fraction of all shortest paths that pass through that node (lower is better)
- `average shortest path length` of a graph is the average of all shortest paths between any combination of nodes (shorter is better)
- `rsd_*` the relative standard deviation of above values is an indicator of the well-formedness (lower is better)
- `diameter` of a graph is the longest shortest path (worst case) (shorter is better, should be log(n))
- `edge connectivity` of a graph is the minimum number of edges that disconnect the graph (network split), wenn deleted (higher is better)

**Comment by heikoheiko** [comment]
Simulation results:
https://docs.google.com/spreadsheets/d/1Xsg0367XibBCg1HegKoInrarLmU_ozwlBLPatv0hhEY/edit?usp=sharing

**Comment by heikoheiko** [comment]
Let's try to describe the requirements and the properties of a viable solution.

## Requirements
### Propagation 
- in a network with `N` participants: messages of size `S` must be received by all nodes in the network in less than `Tmax` seconds and should be received in less than `Tavg` seconds. Assuming average bandwidth `B` the diameter (worst case) of the network must be less than `Dmax`, the average shortest path length should be less than `SPLmax`. There should be no bottlenecks so, therefore the load centrality of every node must be less than `LCmax`

###  Robustness
- in a network with `N` participants: the network must not split if a fraction `F` of the node goes down (due to partial network outages or attacks). Node connectivity must be > `NC`. 

### Bandwidth
- in a network with `N` participants, the bandwidth required by each node should be less than `BWmax`. Therefore the maximum number of peers of each node must be less than `Pmax` while supporting above requirements.

### Sybil Attacks
- in a network with `N` participants: the network must not fail if a fraction `F` of nodes with an average elapsed time `TEavg` since their first appearance,  conspire to attack the network.



# Solution
?

**Comment by heikoheiko** [comment]
for peer selection requirements see:
 https://github.com/ethereum/devp2p/wiki/Peer-Selection-Strategy

**Comment by fjl** [comment]
Closing this because I think everyone is happy with their peer connection strategy now.
