### ISSUE TITLE
Discv5: ECDH shared secret

### ISSUE THREAD

**Issue by jannikluhn** [ethereum/devp2p#134]
We seem to use both the `x` and `y` component of the curve point created by ECDH:

> `ecdh(pubkey, privkey)` creates a secret through elliptic-curve Diffie-Hellman key
agreement. The public key is multiplied by the private key to create a secret ephemeral
key `eph = pubkey * privkey`. The 33-byte secret output is `y || eph.x` where `y` is
`0x02` when `eph.y` is even or `0x03` when `eph.y` is odd.

Unfortunately, the [crypto library](https://github.com/pyca/cryptography) used in Trinity just gives us the `x` component. I assume the same is the case for OpenSSL since the Python library is just a wrapper around it (I haven't confirmed this though). Given this assumption is correct, is there a reason for using both `x` and `y`?

**Comment by fjl** [comment]
Damn. We were actually using just `x` before [this change](https://github.com/ethereum/devp2p/pull/118/files), but then @AgeManning complained about this being hard to implement with their Rust wrapper around secp256k1. I don't care either way since the y coordinate doesn't add much to the security...

**Comment by AgeManning** [comment]
Oh no! Yeah, I figured the more general case was with the y co-ordinate as that was what the C library and subsequent rust library was using.

**Comment by jannikluhn** [comment]
Alright, I found another library that uses the `y || x` format, so I'm happy now.
