### ISSUE TITLE
discv5: 32-byte node-id incompatible with multihash

### ISSUE THREAD

**Issue by AgeManning** [ethereum/devp2p#96]
Libp2p currently uses [multihash](https://github.com/multiformats/multihash) for it's `PeerId`s. These are of length 34 bytes. 

If it is desired to support multihash's in the node-id, perhaps we extend this `node-id` to be a 34 byte object.

**Comment by fjl** [comment]
I don't understand the need for multihash when it comes to node IDs. IMHO multihash makes sense for files in IPFS because you want to be able to verify the file content using the hash function that created the file's address.  If you have a node's record, you can derive the node ID of that record. Once you have the node ID, the information about the hash function used to derive it isn't needed anymore.

**Comment by AgeManning** [comment]
Yep sure. The benefit I saw was that new hashes could be supported easier without upgrading the code (potentially stark friendly hashes which may become prevalent). 

I have no real opinion on this, just thought I'd raise it.
